name: Deploy AVD Environment

on:
  push:
    branches: [ main ]

jobs:
  deploy-avd:
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: avd-rg
      LOCATION: eastus
      HOSTPOOL_NAME: avd-hostpool
      APPGROUP_NAME: avd-appgroup

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login using Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Host Pool and Get Registration Token
        run: |
          hostPoolDeploy=$(az deployment group create \
            --resource-group $RESOURCE_GROUP \
            --template-file ./bicep/hostpool.bicep \
            --parameters hostPoolName=$HOSTPOOL_NAME \
                        location=$LOCATION \
                        expirationTime="$expirationTime" \
            --query properties.outputs \
            --output json)

          registrationToken=$(echo $hostPoolDeploy | jq -r '.registrationToken.value')
          hostPoolId=$(echo $hostPoolDeploy | jq -r '.hostPoolId.value')

          echo "::add-mask::$registrationToken"
          echo "::add-mask::$hostPoolId"

          echo "registrationToken=$registrationToken" >> $GITHUB_ENV
          echo "hostPoolId=$hostPoolId" >> $GITHUB_ENV

      - name: Deploy Application Group
        run: |
          az deployment group create \
            --resource-group $RESOURCE_GROUP \
            --template-file ./bicep/applicationgroup.bicep \
            --parameters appGroupName=$APPGROUP_NAME \
                         location=$LOCATION \
                         hostPoolResourceId=$hostPoolId

      - name: Deploy AVD Workspace
        run: |
          az deployment group create \
            --resource-group avd-rg \
            --template-file ./bicep/workspace.bicep \
            --parameters location="eastus"

      - name: Deploy Session Hosts from custom image
        run: |
          az deployment group create \
            --resource-group avd-rg \
            --template-file ./bicep/sessionhosts.bicep \
            --parameters sessionHostNamePrefix="session-host" \
                         location="eastus" \
                         imageId="${{ secrets.IMAGE_ID }}" \
                         subnetId="${{ secrets.SUBNET_ID }}" \
                         adminUsername="${{ secrets.VM_ADMIN_USERNAME }}" \
                         adminPassword="${{ secrets.VM_ADMIN_PASSWORD }}" \
                         domainToJoin="chinazom.com" \
                         domainJoinUsername="${{ secrets.DOMAIN_JOIN_USERNAME }}" \
                         domainJoinPassword="${{ secrets.DOMAIN_JOIN_PASSWORD }}" \
                         identityId="${{ secrets.IDENTITY_ID }}" \
                         registrationToken="${{ env.registrationToken }}" \
                         hostPoolId="${{ env.hostPoolId }}" \
                         sessionHostCount=1
