name: Deploy AVD Environment

on:
  #push:
    branches: [ main ]

jobs:
  deploy-avd:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login using Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upgrade Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version

      - name: Deploy Host Pool and Get Registration Token
        run: |
          expirationTime=$(date -u -d "+30 days" +"%Y-%m-%dT%H:%M:%SZ")

          hostPoolDeploy=$(az deployment group create \
            --resource-group avd-rg \
            --template-file ./bicep/hostpool.bicep \
            --parameters hostPoolName="avd-hostpool" \
                         location="eastus" \
                         resourceGroupName="avd-rg" \
                         expirationTime="$expirationTime" \
            --query properties.outputs \
            --output json)

          registrationToken=$(echo $hostPoolDeploy | jq -r '.registrationToken.value')
          hostPoolId=$(echo $hostPoolDeploy | jq -r '.hostPoolId.value')

          # Mask values to prevent exposure in logs
          echo "::add-mask::$registrationToken"
          echo "::add-mask::$hostPoolId"

          # Save securely to GitHub Actions environment
          echo "registrationToken=$registrationToken" >> $GITHUB_ENV
          echo "hostPoolId=$hostPoolId" >> $GITHUB_ENV

      - name: Deploy Application Group
        run: |
          az deployment group create \
            --resource-group avd-rg \
            --template-file ./bicep/applicationgroup.bicep \
            --parameters hostPoolName="avd-hostpool" \
                         location="eastus"

      - name: Deploy AVD Workspace
        run: |
          az deployment group create \
            --resource-group avd-rg \
            --template-file ./bicep/workspace.bicep \
            --parameters location="eastus"

      - name: Deploy Session Hosts from custom image
        run: |
          az deployment group create \
            --resource-group avd-rg \
            --template-file ./bicep/sessionhosts.bicep \
            --parameters sessionHostNamePrefix="session-host" \
                         location="eastus" \
                         imageId="${{ secrets.IMAGE_ID }}" \
                         subnetId="${{ secrets.SUBNET_ID }}" \
                         adminUsername="${{ secrets.VM_ADMIN_USERNAME }}" \
                         adminPassword="${{ secrets.VM_ADMIN_PASSWORD }}" \
                         domainToJoin="corp.local" \
                         domainJoinUsername="${{ secrets.DOMAIN_JOIN_USERNAME }}" \
                         domainJoinPassword="${{ secrets.DOMAIN_JOIN_PASSWORD }}" \
                         identityId="${{ secrets.IDENTITY_ID }}" \
                         registrationToken="${{ env.registrationToken }}" \
                         hostPoolId="${{ env.hostPoolId }}" \
                         sessionHostCount=1
